### ISSUE TITLE
Window flag `centered` should be defined in Flags and not to Position

### ISSUE THREAD

**Issue by acf-patrick** [acf-patrick/Entix#20]
```YAML
Title: Test
Size: [1280, 720]
Position: centered
Scenes:
  - main
```
should be
```YAML
Title: Test
Size: [1280, 720]
Flags: [centered]
Scenes:
  - main
```

__PS__ Window always centered wether position is set to centered or not
